// <auto-generated />
using BudgetMiner.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BudgetMiner.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20171013120956_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetMiner.DataAccess.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BudgetOwner");

                    b.Property<string>("Description");

                    b.Property<DateTime>("FirstUse");

                    b.Property<string>("Manufacturer");

                    b.Property<int>("NumberOfUsers");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("BudgetMiner.DataAccess.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationId");

                    b.Property<string>("BudgetOwner");

                    b.Property<decimal>("LicenseCost");

                    b.Property<decimal>("MainCost");

                    b.Property<string>("Name");

                    b.Property<decimal>("YearPercentIncrease");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("BudgetMiner.DataAccess.Entities.YearCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ComponentId");

                    b.Property<decimal>("LicenseDepreciation");

                    b.Property<decimal>("MaintenanceCost");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("YearlyCosts");
                });

            modelBuilder.Entity("BudgetMiner.DataAccess.Entities.Component", b =>
                {
                    b.HasOne("BudgetMiner.DataAccess.Entities.Application", "Application")
                        .WithMany("Components")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BudgetMiner.DataAccess.Entities.YearCost", b =>
                {
                    b.HasOne("BudgetMiner.DataAccess.Entities.Component", "Component")
                        .WithMany("YearlyCosts")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
